POST http://localhost:3333/videos
Content-Type: application/json



{
    "title": "video 1",
    "description": "esse é o primeiro video",
    "duration": 100
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/0cd55565-7d2c-40fe-8dac-7d7a1288bf40
Content-Type: application/json



{
    "title": "video 2",
    "description": "teste put",
    "duration": 100
}

###

DELETE  http://localhost:3333/videos/0cd55565-7d2c-40fe-8dac-7d7a1288bf40
