POST http://localhost:3333/videos
Content-Type: application/json



{
    "title": "video 1",
    "description": "esse é o primeiro video",
    "duration": 100
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/22296a0d-2171-475c-9243-b5bdfc893fde
Content-Type: application/json



{
    "title": "video 3213213",
    "description": "teste put",
    "duration": 100
}

###

DELETE  http://localhost:3333/videos/d940063f-fd5f-4414-809e-9ff0b09af803


